# Generated by Django 3.1.2 on 2020-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('role', models.TextField(default='Reporter')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Default headline', max_length=255)),
                ('subheading', models.TextField(default='Default subheading')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='article.Author')),
            ],
        ),
    ]
