# Generated by Django 3.1.2 on 2020-10-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201028_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='source',
        ),
    ]
