# Generated by Django 3.1.2 on 2020-10-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201028_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
    ]
